server:
  port: 8080
spring:
  application:
    name: letter-service
  rabbitmq:
      host: 192.168.200.128
      port: 5672
      virtual-host: /yukino
      username: yukino
      password: yukino
gmall:
  sms:
    accessKeyId: LTAItNxtDfk7MJMq # 你自己的accessKeyId
    accessKeySecret: HKUIDl21ZM7XoubErXjUFJq84dha8W # 你自己的AccessKeySecret
    signName: 谷粒商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 # 模板名称